const http=require('http'),crypto=require('crypto');const {getPage}=require('./web-panel-runtime');const {getAccess}=require('./web-panel-access');const {getAdminChatIds,getRaw}=require('./config');const {sendMessage}=require('./tg-api');
let server;const sessions=new Map(),attempts=new Map();const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;');
const ip=r=>String(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.socket.remoteAddress||'unknown';
const headers={'X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self' 'unsafe-inline'; img-src 'self' data:"};
async function geo(a){const t=String(getRaw().webPanel?.ipinfoToken||'');if(!t)return'';try{const r=await fetch('https://api.ipinfo.io/lite/'+encodeURIComponent(a),{headers:{Authorization:'Bearer '+t},signal:AbortSignal.timeout(4000)});if(!r.ok)return'';const j=await r.json();return[j.city,j.region,j.country,j.continent].filter(Boolean).join(', ')}catch{return''}}
async function notify(ok,r,u){const a=ip(r),g=await geo(a),m=[ok?'<b>Вход в веб-панель</b>':'<b>Неудачный вход</b>','IP: <code>'+esc(a)+'</code>',g?'Геолокация: <code>'+esc(g)+'</code>':null,u?'Логин: <code>'+esc(u)+'</code>':null].filter(Boolean).join('\n');for(const id of getAdminChatIds())sendMessage(id,m).catch(()=>{})}
function read(r){return new Promise((ok,no)=>{let d='';r.on('data',x=>{d+=x;if(d.length>32768)no(Error('large'))});r.on('end',()=>ok(d));r.on('error',no)})}
function cookie(r){return Object.fromEntries(String(r.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function valid(r,c){const s=sessions.get(cookie(r).maxpanel);return!!(s&&s.g===c.generation&&s.until>Date.now())}
function login(e=''){return '<!doctype html><meta name=viewport content="width=device-width"><style>body{background:#0b1020;color:#fff;font:16px system-ui;display:grid;place-items:center;height:100vh}form{width:320px;background:#151c31;padding:28px;border-radius:20px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:7px 0;border-radius:10px;border:0}button{background:#6574ff;color:#fff}</style><form method=post><h2>MAX Web</h2>'+(e?'<p>'+esc(e)+'</p>':'')+'<input name=u placeholder=Логин required><input name=p type=password placeholder=Пароль required><button>Войти</button></form>'}
function ui(){return '<!doctype html><meta name=viewport content="width=device-width"><style>body{margin:0;background:#080d18;color:white;font:14px system-ui}header{padding:18px;background:#11182a}main{padding:12px}img{width:100%;max-width:1280px;border-radius:14px}</style><header><b>MAX · защищённая веб-панель</b></header><main><p>Живой экран MAX. Клики передаются в текущую сессию.</p><img id=s></main><script>const b=location.pathname.replace(/\\/$/,\"\"),i=document.getElementById(\"s\");function f(){i.src=b+\"/screen?t=\"+Date.now()}setInterval(f,1200);f();i.onclick=e=>{const r=i.getBoundingClientRect();fetch(b+\"/input\",{method:\"POST\",body:JSON.stringify({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height})})}</script>'}
async function handle(r,s){Object.entries(headers).forEach(([k,v])=>s.setHeader(k,v));const c=getAccess(),root='/'+c.path+'/'+c.auth;if(!c.enabled||!r.url.startsWith(root)){s.writeHead(404);return s.end()}
if(r.method==='POST'&&r.url===root){const a=ip(r),st=attempts.get(a)||{n:0,until:0};if(st.until>Date.now()){s.writeHead(429);return s.end('Too many attempts')}const f=new URLSearchParams(await read(r)),u=f.get('u')||'',p=f.get('p')||'',ok=u===c.user&&p===c.pass;notify(ok,r,u);if(!ok){st.n++;if(st.n>=5){st.n=0;st.until=Date.now()+900000}attempts.set(a,st);s.writeHead(401,{'Content-Type':'text/html;charset=utf-8'});return s.end(login('Неверные данные'))}attempts.delete(a);const t=crypto.randomBytes(32).toString('base64url');sessions.set(t,{g:c.generation,until:Date.now()+21600000});s.writeHead(302,{'Set-Cookie':'maxpanel='+t+'; HttpOnly; Secure; SameSite=Strict; Path='+root+'; Max-Age=21600',Location:root});return s.end()}
if(!valid(r,c)){s.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});return s.end(login())}
if(r.url.startsWith(root+'/screen')){const p=getPage();if(!p){s.writeHead(503);return s.end()}try{const b=await p.screenshot({type:'jpeg',quality:65});s.writeHead(200,{'Content-Type':'image/jpeg','Cache-Control':'no-store'});return s.end(b)}catch{s.writeHead(503);return s.end()}}
if(r.method==='POST'&&r.url===root+'/input'){const p=getPage();if(!p){s.writeHead(503);return s.end()}try{const d=JSON.parse(await read(r)),v=p.viewportSize()||{width:1280,height:900};await p.mouse.click(Math.round(d.x*v.width),Math.round(d.y*v.height));s.writeHead(204);return s.end()}catch{s.writeHead(400);return s.end()}}
s.writeHead(200,{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'});s.end(ui())}
function start(){if(server)return;const c=getAccess();server=http.createServer((r,s)=>handle(r,s).catch(()=>{s.writeHead(500);s.end()}));server.listen(Number(c.port||3848),'127.0.0.1')}module.exports={start};
