const http=require('http'),crypto=require('crypto');const {getPage}=require('./web-panel-runtime');const {getAccess}=require('./web-panel-access');const {getAdminChatIds,getRaw}=require('./config');const {sendMessage}=require('./tg-api');
let server;const sessions=new Map(),attempts=new Map();const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;');
const ip=r=>String(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.socket.remoteAddress||'unknown';
const headers={'X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self' 'unsafe-inline'; img-src 'self' data:"};
async function geo(a){const t=String(getRaw().webPanel?.ipinfoToken||'');if(!t)return'';try{const r=await fetch('https://api.ipinfo.io/lite/'+encodeURIComponent(a),{headers:{Authorization:'Bearer '+t},signal:AbortSignal.timeout(4000)});if(!r.ok)return'';const j=await r.json();return[j.city,j.region,j.country,j.continent].filter(Boolean).join(', ')}catch{return''}}
async function notify(ok,r,u){const a=ip(r),g=await geo(a),m=[ok?'<b>Вход в веб-панель</b>':'<b>Неудачный вход</b>','IP: <code>'+esc(a)+'</code>',g?'Геолокация: <code>'+esc(g)+'</code>':null,u?'Логин: <code>'+esc(u)+'</code>':null].filter(Boolean).join('\n');for(const id of getAdminChatIds())sendMessage(id,m).catch(()=>{})}
function read(r){return new Promise((ok,no)=>{let d='';r.on('data',x=>{d+=x;if(d.length>32768)no(Error('large'))});r.on('end',()=>ok(d));r.on('error',no)})}
function cookie(r){return Object.fromEntries(String(r.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function valid(r,c){const s=sessions.get(cookie(r).maxpanel);return!!(s&&s.g===c.generation&&s.until>Date.now())}
function login(e=''){return '<!doctype html><meta name=viewport content="width=device-width"><style>body{background:#0b1020;color:#fff;font:16px system-ui;display:grid;place-items:center;height:100vh}form{width:320px;background:#151c31;padding:28px;border-radius:20px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:7px 0;border-radius:10px;border:0}button{background:#6574ff;color:#fff}</style><form method=post><h2>MAX Web</h2>'+(e?'<p>'+esc(e)+'</p>':'')+'<input name=u placeholder=Логин required><input name=p type=password placeholder=Пароль required><button>Войти</button></form>'}
function ui(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#05070b}body{font-family:system-ui;user-select:none}
#stage{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;background:#05070b;touch-action:none;cursor:default}
#s{display:block;max-width:100vw;max-height:100vh;width:auto;height:auto;object-fit:contain;pointer-events:none}
#state{position:fixed;top:8px;left:50%;transform:translateX(-50%);z-index:2;padding:5px 9px;border-radius:9px;background:#0009;color:#fff;font:12px system-ui;opacity:.65;pointer-events:none}
</style></head><body><div id="stage"><img id="s" draggable="false"></div><div id="state">MAX</div><script>
const b=location.pathname.replace(/\\/$/,""),stage=document.getElementById("stage"),img=document.getElementById("s"),state=document.getElementById("state");
let busy=false,lastMove=0,pointerDown=false,screenW=1280,screenH=900;
async function refresh(){if(busy)return;busy=true;const n=new Image();n.onload=()=>{img.src=n.src;screenW=n.naturalWidth||screenW;screenH=n.naturalHeight||screenH;state.textContent="MAX";busy=false};n.onerror=()=>{state.textContent="Переподключение…";busy=false};n.src=b+"/screen?t="+Date.now()}
setInterval(refresh,350);refresh();
function pos(e){const r=img.getBoundingClientRect();if(!r.width||!r.height)return null;if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return null;return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
function send(type,e,extra={}){const q=pos(e);if(!q)return;fetch(b+"/input",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...q,type,...extra})}).catch(()=>{})}
stage.addEventListener("pointermove",e=>{const now=performance.now();if(now-lastMove<25)return;lastMove=now;send("move",e)});
stage.addEventListener("pointerdown",e=>{if(e.button!==0)return;pointerDown=true;stage.setPointerCapture?.(e.pointerId);send("down",e,{button:"left"})});
stage.addEventListener("pointerup",e=>{if(!pointerDown)return;pointerDown=false;send("up",e,{button:"left"});stage.releasePointerCapture?.(e.pointerId)});
stage.addEventListener("pointercancel",e=>{if(pointerDown){pointerDown=false;send("up",e,{button:"left"})}});
stage.addEventListener("contextmenu",e=>{e.preventDefault();send("click",e,{button:"right"})});
stage.addEventListener("wheel",e=>{e.preventDefault();send("wheel",e,{deltaX:e.deltaX,deltaY:e.deltaY})},{passive:false});
window.addEventListener("keydown",e=>{if(["F5","F11"].includes(e.key))return;fetch(b+"/input",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"key",key:e.key,code:e.code,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,meta:e.metaKey})}).catch(()=>{});if(e.key!=="Tab")return;e.preventDefault()});
</script></body></html>`}
async function handle(r,s){Object.entries(headers).forEach(([k,v])=>s.setHeader(k,v));const c=getAccess(),root='/'+c.path+'/'+c.auth;if(!c.enabled||!r.url.startsWith(root)){s.writeHead(404);return s.end()}
if(r.method==='POST'&&r.url===root){const a=ip(r),st=attempts.get(a)||{n:0,until:0};if(st.until>Date.now()){s.writeHead(429);return s.end('Too many attempts')}const f=new URLSearchParams(await read(r)),u=f.get('u')||'',p=f.get('p')||'',ok=u===c.user&&p===c.pass;notify(ok,r,u);if(!ok){st.n++;if(st.n>=5){st.n=0;st.until=Date.now()+900000}attempts.set(a,st);s.writeHead(401,{'Content-Type':'text/html;charset=utf-8'});return s.end(login('Неверные данные'))}attempts.delete(a);const t=crypto.randomBytes(32).toString('base64url');sessions.set(t,{g:c.generation,until:Date.now()+21600000});s.writeHead(302,{'Set-Cookie':'maxpanel='+t+'; HttpOnly; Secure; SameSite=Strict; Path='+root+'; Max-Age=21600',Location:root});return s.end()}
if(!valid(r,c)){s.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});return s.end(login())}
if(r.url.startsWith(root+'/screen')){const p=await getPage();if(!p){s.writeHead(503);return s.end()}try{const b=await p.screenshot({type:'jpeg',quality:65});s.writeHead(200,{'Content-Type':'image/jpeg','Cache-Control':'no-store'});return s.end(b)}catch{s.writeHead(503);return s.end()}}
if(r.method==='POST'&&r.url===root+'/input'){const p=await getPage();if(!p){s.writeHead(503);return s.end()}try{const d=JSON.parse(await read(r)),v=p.viewportSize()||{width:1280,height:900};const x=Math.max(0,Math.min(v.width-1,Math.round(Number(d.x||0)*v.width))),y=Math.max(0,Math.min(v.height-1,Math.round(Number(d.y||0)*v.height)));switch(d.type){case'move':await p.mouse.move(x,y);break;case'down':await p.mouse.move(x,y);await p.mouse.down({button:d.button==='right'?'right':'left'});break;case'up':await p.mouse.move(x,y);await p.mouse.up({button:d.button==='right'?'right':'left'});break;case'click':await p.mouse.click(x,y,{button:d.button==='right'?'right':'left'});break;case'wheel':await p.mouse.move(x,y);await p.mouse.wheel(Number(d.deltaX)||0,Number(d.deltaY)||0);break;case'key':{const mods=[];if(d.ctrl)mods.push('Control');if(d.alt)mods.push('Alt');if(d.shift)mods.push('Shift');if(d.meta)mods.push('Meta');for(const m of mods)await p.keyboard.down(m);try{const k=String(d.key||'');if(k.length===1&&!d.ctrl&&!d.alt&&!d.meta)await p.keyboard.insertText(k);else if(k)await p.keyboard.press(k===' '?'Space':k)}finally{for(const m of mods.reverse())await p.keyboard.up(m)}break}default:await p.mouse.click(x,y)}s.writeHead(204);return s.end()}catch(err){console.error('webPanel input:',err.message);s.writeHead(400);return s.end()}}
s.writeHead(200,{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'});s.end(ui())}
function start(){if(server)return;const c=getAccess();server=http.createServer((r,s)=>handle(r,s).catch(()=>{s.writeHead(500);s.end()}));server.listen(Number(c.port||3848),'127.0.0.1')}module.exports={start};
